package db

const InternalLang = `[
  {"label": "简体中文（中国大陆）", "value": "zh-CN"},
  {"label": "简体中文（新加坡）", "value": "zh-SG"},
  {"label": "简体中文", "value": "zh-Hans"},
  {"label": "简体中文（中国大陆）", "value": "zh-Hans-CN"},
  {"label": "繁体中文（台湾）", "value": "zh-TW"},
  {"label": "繁体中文（香港）", "value": "zh-HK"},
  {"label": "繁体中文（澳门）", "value": "zh-MO"},
  {"label": "繁体中文", "value": "zh-Hant"},
  {"label": "繁体中文（台湾）", "value": "zh-Hant-TW"},
  {"label": "繁体中文（香港）", "value": "zh-Hant-HK"},
  {"label": "中文", "value": "zh"},
  {"label": "英语（美国）", "value": "en-US"},
  {"label": "英语（英国）", "value": "en-GB"},
  {"label": "英语（加拿大）", "value": "en-CA"},
  {"label": "英语（澳大利亚）", "value": "en-AU"},
  {"label": "英语（印度）", "value": "en-IN"},
  {"label": "英语", "value": "en"},
  {"label": "日语（日本）", "value": "ja-JP"},
  {"label": "日语", "value": "ja"},
  {"label": "韩语（韩国）", "value": "ko-KR"},
  {"label": "韩语", "value": "ko"},
  {"label": "法语（法国）", "value": "fr-FR"},
  {"label": "法语（加拿大）", "value": "fr-CA"},
  {"label": "法语", "value": "fr"},
  {"label": "德语（德国）", "value": "de-DE"},
  {"label": "德语（奥地利）", "value": "de-AT"},
  {"label": "德语", "value": "de"},
  {"label": "西班牙语（西班牙）", "value": "es-ES"},
  {"label": "西班牙语（墨西哥）", "value": "es-MX"},
  {"label": "西班牙语（美国）", "value": "es-US"},
  {"label": "西班牙语", "value": "es"},
  {"label": "俄语（俄罗斯）", "value": "ru-RU"},
  {"label": "俄语", "value": "ru"},
  {"label": "葡萄牙语（葡萄牙）", "value": "pt-PT"},
  {"label": "葡萄牙语（巴西）", "value": "pt-BR"},
  {"label": "葡萄牙语", "value": "pt"},
  {"label": "阿拉伯语（沙特阿拉伯）", "value": "ar-SA"},
  {"label": "阿拉伯语（埃及）", "value": "ar-EG"},
  {"label": "阿拉伯语", "value": "ar"},
  {"label": "意大利语（意大利）", "value": "it-IT"},
  {"label": "意大利语", "value": "it"},
  {"label": "荷兰语（荷兰）", "value": "nl-NL"},
  {"label": "荷兰语（比利时）", "value": "nl-BE"},
  {"label": "荷兰语", "value": "nl"},
  {"label": "土耳其语（土耳其）", "value": "tr-TR"},
  {"label": "土耳其语", "value": "tr"},
  {"label": "越南语（越南）", "value": "vi-VN"},
  {"label": "越南语", "value": "vi"},
  {"label": "泰语（泰国）", "value": "th-TH"},
  {"label": "泰语", "value": "th"},
  {"label": "印地语（印度）", "value": "hi-IN"},
  {"label": "印地语", "value": "hi"}
]`

const InternalTimezone = `[
  {"label": "中国标准时间 (北京)", "value": "Asia/Shanghai"},
  {"label": "中国标准时间 (乌鲁木齐)", "value": "Asia/Urumqi"},
  {"label": "香港时间", "value": "Asia/Hong_Kong"},
  {"label": "台北时间", "value": "Asia/Taipei"},
  {"label": "澳门时间", "value": "Asia/Macau"},
  {"label": "美国东部时间 (纽约)", "value": "America/New_York"},
  {"label": "美国中部时间 (芝加哥)", "value": "America/Chicago"},
  {"label": "美国山区时间 (丹佛)", "value": "America/Denver"},
  {"label": "美国太平洋时间 (洛杉矶)", "value": "America/Los_Angeles"},
  {"label": "美国阿拉斯加时间 (安克雷奇)", "value": "America/Anchorage"},
  {"label": "美国夏威夷时间 (檀香山)", "value": "Pacific/Honolulu"},
  {"label": "英国时间 (伦敦)", "value": "Europe/London"},
  {"label": "欧洲中部时间 (巴黎/柏林)", "value": "Europe/Paris"},
  {"label": "东欧时间 (莫斯科)", "value": "Europe/Moscow"},
  {"label": "中东时间 (迪拜)", "value": "Asia/Dubai"},
  {"label": "印度标准时间 (新德里)", "value": "Asia/Kolkata"},
  {"label": "日本标准时间 (东京)", "value": "Asia/Tokyo"},
  {"label": "韩国标准时间 (首尔)", "value": "Asia/Seoul"},
  {"label": "澳大利亚东部时间 (悉尼)", "value": "Australia/Sydney"},
  {"label": "澳大利亚中部时间 (阿德莱德)", "value": "Australia/Adelaide"},
  {"label": "澳大利亚西部时间 (珀斯)", "value": "Australia/Perth"},
  {"label": "新西兰时间 (奥克兰)", "value": "Pacific/Auckland"},
  {"label": "新加坡时间", "value": "Asia/Singapore"},
  {"label": "马来西亚时间 (吉隆坡)", "value": "Asia/Kuala_Lumpur"},
  {"label": "泰国时间 (曼谷)", "value": "Asia/Bangkok"},
  {"label": "越南时间 (河内)", "value": "Asia/Ho_Chi_Minh"},
  {"label": "印度尼西亚西部时间 (雅加达)", "value": "Asia/Jakarta"},
  {"label": "印度尼西亚中部时间 (巴厘岛)", "value": "Asia/Makassar"},
  {"label": "印度尼西亚东部时间 (查亚普拉)", "value": "Asia/Jayapura"},
  {"label": "菲律宾时间 (马尼拉)", "value": "Asia/Manila"},
  {"label": "加拿大东部时间 (多伦多)", "value": "America/Toronto"},
  {"label": "加拿大中部时间 (温尼伯)", "value": "America/Winnipeg"},
  {"label": "加拿大山地时间 (埃德蒙顿)", "value": "America/Edmonton"},
  {"label": "加拿大太平洋时间 (温哥华)", "value": "America/Vancouver"},
  {"label": "巴西东部时间 (圣保罗)", "value": "America/Sao_Paulo"},
  {"label": "巴西西部时间 (马瑙斯)", "value": "America/Manaus"},
  {"label": "阿根廷时间 (布宜诺斯艾利斯)", "value": "America/Argentina/Buenos_Aires"},
  {"label": "墨西哥时间 (墨西哥城)", "value": "America/Mexico_City"},
  {"label": "南非时间 (约翰内斯堡)", "value": "Africa/Johannesburg"},
  {"label": "埃及时间 (开罗)", "value": "Africa/Cairo"},
  {"label": "沙特阿拉伯时间 (利雅得)", "value": "Asia/Riyadh"},
  {"label": "以色列时间 (耶路撒冷)", "value": "Asia/Jerusalem"},
  {"label": "土耳其时间 (伊斯坦布尔)", "value": "Europe/Istanbul"},
  {"label": "协调世界时 (UTC)", "value": "UTC"},
  {"label": "格林威治标准时间", "value": "GMT"}
]`
